server:
  port: 8081

#数据库配置：
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wc041114
    url: jdbc:mysql://localhost:3306/vue?
  mvc:
    static-path-pattern: /**
  web:
    resources:
          static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.static-path}
web:
  static-path: /www/wwwroot/demo/dist/ # 前端dist目录路径
# 配置mybatis实体和xml映射
mybatis:
  ## 映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

